//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtCaseApi.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CaseFile
    {
        public int CaseFileID { get; set; }
        public string FileDate { get; set; }
        public string JudgmentDate { get; set; }
        public int CaseID { get; set; }
        public virtual Case Case { get; set; }
    }
}
